controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_cours:
    path: /cours
    controller: App\Controller\CoursController::index

app_cours_lister:
    path: /cours/lister
    controller: App\Controller\CoursController::listerCours

app_cours_consulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulterCours

app_cours_ajouter:
    path: /cours/ajouter
    controller: App\Controller\CoursController::ajouterCours

app_cours_supprimer:
    path: /cours/supprimer/{id}
    controller: App\Controller\CoursController::supprimerCours

app_cours_modifier:
    path: /cours/modifier/{id}
    controller: App\Controller\CoursController::modifierCours

app_eleve_lister:
    path: /eleve/lister
    controller: App\Controller\EleveController::listerEleves