# config/services.yaml

# Paramètres généraux de l'application
parameters:
    # Vous pouvez définir des paramètres globaux ici, par exemple une clé API, une URL de base, etc.
    app.some_parameter: 'value'

# Configuration des services
services:
    # Par défaut, tous les services sont automatiquement injectés
    _defaults:
        autowire: true      # Symfony injecte automatiquement les dépendances dans vos services
        autoconfigure: true # Symfony enregistre automatiquement vos services comme commandes, abonnés d'événements, etc.

    # Permet de déclarer toutes les classes dans le dossier src/
    # Cela signifie que toutes les classes dans le dossier src seront considérées comme des services.
    # Symfony va automatiquement les enregistrer.
    App\:
        resource: '../src/'  # Charge toutes les classes du dossier src/
        exclude:
            - '../src/DependencyInjection/'  # Exclut ce dossier
            - '../src/Entity/'  # Exclut ce dossier (les entités ne sont pas des services)
            - '../src/Kernel.php'  # Exclut Kernel.php qui est déjà configuré ailleurs

    # Définir un service explicite pour LoginSuccessHandler (par exemple)
    App\Security\LoginSuccessHandler:
        arguments:
            $router: '@router'  # Injecte le service 'router' dans ce service
